[package]
name = "testpackage"
version = "1.2.0"
description = "testing a new package"
repository = "https://github.com/sam-thetutor/testpackage"
keywords = [ "testing" ]
license = "MIT"

[dependencies]
base = "0.10.0"