[package]
name = "testpackage"
version = "1.2.2"
description = "testing a new package"
repository = "https://github.com/sam-thetutor/testpackage"
keywords = [ "testing" ]
license = "MIT"

[dependencies]
base = "0.10.0"

[toolchain]
moc = "0.10.3"
wasmtime = "16.0.0"
